### ISSUE TITLE
pwd command not found.

### ISSUE THREAD

**Issue by Arnav-Khare** [imabp/LearnBasicLinuxTerminal#16]
After entering on second stage when a user enter pwd command, the app shows "Command not found!"

![Screenshot from 2020-12-10 18-03-21](https://user-images.githubusercontent.com/55575931/101773804-4603be80-3b13-11eb-982c-c396d45b4b59.png)

**Comment by imabp** [comment]
@Arnav-Khare, Thank you for the concern
this is the project at the development stage and the issue is known. 
It's open for contributions from KWOC Participants.
If you are a KWOC Participant. Do Join the communication channel.

**Comment by imabp** [comment]
Thank you @Arnav-Khare for the confirmation at Gitter.
Yes, you may proceed to contribute to this project.
I am happy to have you on board.
😊😊
Ping me up, if you need any help :)
Before that, just see the #17 Issue, if you are not clear about the codebase structure. :)

**Comment by Arnav-Khare** [comment]
okay sir..
